# Generated by Django 4.1 on 2022-08-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_chatmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='chat_status',
            field=models.BooleanField(default=False),
        ),
    ]
