# Generated by Django 4.1 on 2022-08-10 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_client_chat_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmodel',
            old_name='admin_chat',
            new_name='read_chat',
        ),
        migrations.RenameField(
            model_name='chatmodel',
            old_name='client_chat',
            new_name='write_chat',
        ),
    ]
