from django.urls import path
from .views import (
         FeedView,
         ProductAPIView,
         BannnerAPIView,
         CellProductAddAPIView,
         CustomerPurchasRemoveProductAPIView,
         CellProductAPIView,
         CartView,
         CustomerPurchasAPIView,
         ProductDetailView,
         ProductDetailAPIView,
         ProductdetailAPIView,
         ProductsView,
         ProductAllAPIView,
         CardShopAPIView,
         SearchProducAPIView,
         FooList,
         ShoppingHistoryView,
         ShoppingHistoryAPIView,
         pdf_report_create
)
app_name = 'products'
urlpatterns = [
    path('paginator', FooList.as_view(),name='feesdd'),
    path('', FeedView.as_view(),name='feed'),
    path('cart', CartView.as_view(),name='cart'),
    path('products', ProductsView.as_view(),name='allproduct'),
    path('shopping/history', ShoppingHistoryView.as_view(),name='history'),
    path('shopping/history/pdf/<int:id>', pdf_report_create,name='history'),
    path('api/shopping/history', ShoppingHistoryAPIView.as_view(),name='history'),
    path('product/detail/<int:id>', ProductDetailView.as_view(),name='detail'),
    path('api/product/all', ProductAllAPIView.as_view(),name='productall'),
    path('api/product/search', SearchProducAPIView.as_view(),name='search'),
    path('api/product/detail', ProductdetailAPIView.as_view(),name='detailapi'),
    path('api/products', ProductAPIView.as_view(),name='apifeed'),
    path('api/product/card/count', CardShopAPIView.as_view(),name='count'),
    path('api/purchas/product', CustomerPurchasAPIView.as_view(),name='purchas'),
    path('api/cell/product', CellProductAPIView.as_view(),name='cell'),
    path('api/benner', BannnerAPIView.as_view(),name='benner'),
    path('api/product/detail/<int:id>', ProductDetailAPIView.as_view(),name='detail'),
    path('api/cell/product/add/<int:id>', CellProductAddAPIView.as_view(),name='cell_product'),
    path('api/cell/product/remove/<int:id>', CustomerPurchasRemoveProductAPIView.as_view(),name='cell_product'),
]