# Generated by Django 4.0.6 on 2022-07-31 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bannner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_describtion', models.CharField(default='not found this product', max_length=250, verbose_name="Banner haqida ma'limot")),
                ('banner_title', models.CharField(default='not found this banner', max_length=150, verbose_name='Banner title')),
                ('banner_image', models.ImageField(default='product_image/bannernew.jpg', upload_to='banner_image/', verbose_name='Banner rasmi')),
                ('banner_skidka_price', models.CharField(default='not found this banner', max_length=50, verbose_name='Banner chegirma')),
            ],
        ),
        migrations.CreateModel(
            name='CellProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_count', models.IntegerField(default=1, verbose_name='Mahsulot soni')),
                ('total_price', models.FloatField(default=0, verbose_name='Umumiy narxi')),
                ('data_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPurchas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(default=0, verbose_name='Umumiy narxi')),
                ('data_time', models.DateTimeField(auto_now_add=True, verbose_name='Sotib olingan vaqt')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='not found this product', max_length=150, verbose_name='Mahsulot nomi')),
                ('product_price', models.FloatField(default=0, verbose_name='Mahsulot narxi')),
                ('product_image', models.ImageField(default='product_image/productnew.jpg', upload_to='product_image/', verbose_name='Mahsulot rasmi')),
                ('product_skidka_price', models.FloatField(default=0, verbose_name='Mahsulotning skidka narxi')),
                ('product_type', models.CharField(default='', max_length=100)),
                ('product_description', models.CharField(default='This product', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.DateTimeField(auto_now_add=True, verbose_name='Sotib olingan vaqt')),
            ],
        ),
    ]
