# Generated by Django 4.0.6 on 2022-07-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpurchas',
            name='product_status',
            field=models.BooleanField(default=False),
        ),
    ]
