# Generated by Django 4.0.6 on 2022-07-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_customerpurchas_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellproduct',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
