# Generated by Django 4.0.6 on 2022-07-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_cellproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinghistory',
            name='product',
            field=models.ManyToManyField(to='products.customerpurchas', verbose_name='Xaridalar Royhati'),
        ),
    ]
